import type { Experience } from '@/types';

export const experiencesData: Experience[] = [
    // SENDERISMO (6)
    {
        id: '1',
        slug: 'trekking-atlas',
        title_es: 'Trekking por el Alto Atlas',
        title_en: 'High Atlas Trekking',
        category: 'senderismo',
        destination: 'Marrakech',
        difficulty: 'moderado',
        duration_days: 3,
        price_from_usd: 280,
        rating: 4.9,
        reviews_count: 67,
        badge_es: 'Más popular',
        badge_en: 'Most Popular',
        badge_color: '#F4A261',
        image: '/images/trekking-atlas/trekking-atlas1.webp',
    },
    {
        id: '13',
        slug: 'cascadas-ouirgane',
        title_es: 'Ruta por las Cascadas de Ouirgane',
        title_en: 'Route to Ouirgane Waterfalls',
        category: 'senderismo',
        destination: 'Marrakech',
        difficulty: 'facil',
        duration_days: 1,
        price_from_usd: 55,
        rating: 4.6,
        reviews_count: 43,
        image: '/images/trekking-atlas/trekking-atlas2.webp',
    },
    {
        id: '14',
        slug: 'valle-imlil',
        title_es: 'Valle de Imlil y Monte Toubkal',
        title_en: 'Imlil Valley and Mount Toubkal',
        category: 'senderismo',
        destination: 'Marrakech',
        difficulty: 'dificil',
        duration_days: 2,
        price_from_usd: 190,
        rating: 4.8,
        reviews_count: 52,
        image: '/images/trekking-atlas/trekking-atlas17.webp',
    },
    {
        id: '15',
        slug: 'souss-massa',
        title_es: 'Senderismo en el Parque Nacional Souss-Massa',
        title_en: 'Hiking in Souss-Massa National Park',
        category: 'senderismo',
        destination: 'Essaouira',
        difficulty: 'facil',
        duration_days: 1,
        price_from_usd: 65,
        rating: 4.5,
        reviews_count: 28,
        image: '/images/essaouira/essaouira14.jpg',
    },
    {
        id: '16',
        slug: 'tif-nou-ourika',
        title_es: 'Ruta de los 7 Pozos de Ourika',
        title_en: 'Route of the 7 Wells of Ourika',
        category: 'senderismo',
        destination: 'Marrakech',
        difficulty: 'facil',
        duration_days: 1,
        price_from_usd: 50,
        rating: 4.7,
        reviews_count: 89,
        image: '/images/trekking-atlas/trekking-atlas3.webp',
    },
    {
        id: '17',
        slug: 'trek-marrakech-essaouira',
        title_es: 'Trekking entre Marrakech y Essaouira',
        title_en: 'Trekking between Marrakech and Essaouira',
        category: 'senderismo',
        destination: 'Marrakech',
        difficulty: 'moderado',
        duration_days: 4,
        price_from_usd: 450,
        rating: 4.9,
        reviews_count: 34,
        image: '/images/trekking-atlas/trekking-atlas4.webp',
    },

    // DESIERTO (6)
    {
        id: '2',
        slug: 'desierto-merzouga',
        title_es: 'Aventura en el Desierto de Merzouga',
        title_en: 'Merzouga Desert Adventure',
        category: 'desierto',
        destination: 'Merzouga',
        difficulty: 'facil',
        duration_days: 2,
        price_from_usd: 180,
        rating: 4.8,
        reviews_count: 124,
        badge_es: 'Top Rated',
        badge_en: 'Top Rated',
        badge_color: '#2D6A4F',
        image: '/images/merzouga/merzouga1.jpg',
    },
    {
        id: '10',
        slug: 'noche-desierto',
        title_es: 'Noche Estrellada en el Sáhara',
        title_en: 'Starry Night in the Sahara',
        category: 'desierto',
        destination: 'Merzouga',
        difficulty: 'facil',
        duration_days: 1,
        price_from_usd: 120,
        rating: 4.9,
        reviews_count: 89,
        image: '/images/merzouga/merzouga6.jpg',
    },
    {
        id: '18',
        slug: 'merzouga-erg-chebbi',
        title_es: 'Amanecer en Erg Chebbi',
        title_en: 'Sunrise in Erg Chebbi',
        category: 'desierto',
        destination: 'Merzouga',
        difficulty: 'facil',
        duration_days: 1,
        price_from_usd: 95,
        rating: 4.7,
        reviews_count: 156,
        image: '/images/merzouga/merzouga7.jpg',
    },
    {
        id: '19',
        slug: 'merzouga-fez',
        title_es: 'Ruta del Desierto: Merzouga a Fez',
        title_en: 'Desert Route: Merzouga to Fez',
        category: 'desierto',
        destination: 'Merzouga',
        difficulty: 'moderado',
        duration_days: 3,
        price_from_usd: 320,
        rating: 4.8,
        reviews_count: 67,
        image: '/images/merzouga/merzouga1.jpg',
    },
    {
        id: '20',
        slug: 'atv-desierto',
        title_es: 'Aventura en ATV por las Dunas',
        title_en: 'ATV Adventure through the Dunes',
        category: 'desierto',
        destination: 'Merzouga',
        difficulty: 'facil',
        duration_days: 1,
        price_from_usd: 85,
        rating: 4.6,
        reviews_count: 92,
        image: '/images/merzouga/merzouga1.jpg',
    },
    {
        id: '21',
        slug: 'camel-trekking',
        title_es: 'Camel Trekking de 3 Días',
        title_en: '3-Day Camel Trekking',
        category: 'desierto',
        destination: 'Merzouga',
        difficulty: 'facil',
        duration_days: 3,
        price_from_usd: 280,
        rating: 4.9,
        reviews_count: 78,
        image: '/images/merzouga/merzouga1.jpg',
    },

    // CULTURA (6)
    {
        id: '3',
        slug: 'tour-fez',
        title_es: 'Tour Guiado por Fez Medina',
        title_en: 'Guided Tour of Fez Medina',
        category: 'cultura',
        destination: 'Fez',
        difficulty: 'facil',
        duration_days: 1,
        price_from_usd: 75,
        rating: 4.9,
        reviews_count: 89,
        image: '/images/fes/fes3.webp',
    },
    {
        id: '22',
        slug: 'tour-marrakech',
        title_es: 'Descubre Marrakech',
        title_en: 'Discover Marrakech',
        category: 'cultura',
        destination: 'Marrakech',
        difficulty: 'facil',
        duration_days: 1,
        price_from_usd: 65,
        rating: 4.8,
        reviews_count: 134,
        image: '/images/marrakech/marrakech6.jpg',
    },
    {
        id: '6',
        slug: 'tour-casablanca-rabat',
        title_es: 'Tour Casablanca y Rabat',
        title_en: 'Casablanca and Rabat Tour',
        category: 'cultura',
        destination: 'Casablanca',
        difficulty: 'facil',
        duration_days: 1,
        price_from_usd: 85,
        rating: 4.5,
        reviews_count: 32,
        image: '/images/casa & rabat/casa1.jpg',
    },
    {
        id: '9',
        slug: 'tangier',
        title_es: 'Excursión a Tanger',
        title_en: 'Excursion to Tangier',
        category: 'cultura',
        destination: 'Tangier',
        difficulty: 'facil',
        duration_days: 1,
        price_from_usd: 120,
        rating: 4.4,
        reviews_count: 78,
        image: '/images/tanger/tanger1.jpg',
    },
    {
        id: '23',
        slug: 'tour-imperial-cities',
        title_es: 'Tour por las Ciudades Imperiales',
        title_en: 'Imperial Cities Tour',
        category: 'cultura',
        destination: 'Fez',
        difficulty: 'facil',
        duration_days: 5,
        price_from_usd: 650,
        rating: 4.9,
        reviews_count: 56,
        image: '/images/fes/fes12.webp',
    },
    {
        id: '24',
        slug: 'tour-marrakech-esensial',
        title_es: 'Marrakech Esencial: Medina y Jardines',
        title_en: 'Essential Marrakech: Medina and Gardens',
        category: 'cultura',
        destination: 'Marrakech',
        difficulty: 'facil',
        duration_days: 1,
        price_from_usd: 55,
        rating: 4.7,
        reviews_count: 98,
        image: '/images/marrakech/marrakech1.jpg',
    },

    // COSTA (6)
    {
        id: '4',
        slug: 'essaouira',
        title_es: 'Excursión a Essaouira',
        title_en: 'Excursion to Essaouira',
        category: 'costa',
        destination: 'Essaouira',
        difficulty: 'facil',
        duration_days: 1,
        price_from_usd: 65,
        rating: 4.7,
        reviews_count: 156,
        image: '/images/essaouira/essaouira1.jpg',
    },
    {
        id: '25',
        slug: 'sur-essaouira',
        title_es: 'Clase de Surf en Essaouira',
        title_en: 'Surf Class in Essaouira',
        category: 'costa',
        destination: 'Essaouira',
        difficulty: 'facil',
        duration_days: 1,
        price_from_usd: 45,
        rating: 4.9,
        reviews_count: 78,
        image: '/images/essaouira/essaouira2.jpg',
    },
    {
        id: '12',
        slug: 'kitesurf-essaouira',
        title_es: 'Curso de Kitesurf en Essaouira',
        title_en: 'Kitesurf Course in Essaouira',
        category: 'costa',
        destination: 'Essaouira',
        difficulty: 'moderado',
        duration_days: 3,
        price_from_usd: 280,
        rating: 4.8,
        reviews_count: 42,
        image: '/images/essaouira/essaouira4.jpg',
    },
    {
        id: '26',
        slug: 'asilah',
        title_es: 'Excursión a Asilah desde Tanger',
        title_en: 'Excursion to Asilah from Tangier',
        category: 'costa',
        destination: 'Tangier',
        difficulty: 'facil',
        duration_days: 1,
        price_from_usd: 55,
        rating: 4.6,
        reviews_count: 34,
        image: '/images/tanger/tanger2.jpg',
    },
    {
        id: '27',
        slug: 'el-jadida',
        title_es: 'Descubre El Jadida y Porto',
        title_en: 'Discover El Jadida and Porto',
        category: 'costa',
        destination: 'Casablanca',
        difficulty: 'facil',
        duration_days: 1,
        price_from_usd: 60,
        rating: 4.5,
        reviews_count: 28,
        image: '/images/casa & rabat/casa2.jpg',
    },
    {
        id: '28',
        slug: 'dakhla',
        title_es: 'Aventura en Dakhla: Kitesurf Paradise',
        title_en: 'Dakhla Adventure: Kitesurf Paradise',
        category: 'costa',
        destination: 'Dakhla',
        difficulty: 'moderado',
        duration_days: 5,
        price_from_usd: 550,
        rating: 4.9,
        reviews_count: 67,
        image: '/images/essaouira/essaouira1.jpg',
    },

    // MONTANA (6)
    {
        id: '7',
        slug: 'trekking-toubkal',
        title_es: 'Ascensión al Toubkal (4167m)',
        title_en: 'Toubkal Ascent (4167m)',
        category: 'montana',
        destination: 'Marrakech',
        difficulty: 'dificil',
        duration_days: 2,
        price_from_usd: 220,
        rating: 5.0,
        reviews_count: 28,
        badge_es: 'Para expertos',
        badge_en: 'For experts',
        badge_color: '#D62828',
        image: '/images/trekking-atlas/trekking-atlas5.jpg',
    },
    {
        id: '8',
        slug: 'valley-dades',
        title_es: 'Ruta de las Mil Kasbahs',
        title_en: 'Route of the Thousand Kasbahs',
        category: 'montana',
        destination: 'Ouarzazate',
        difficulty: 'moderado',
        duration_days: 2,
        price_from_usd: 165,
        rating: 4.7,
        reviews_count: 51,
        image: '/images/trekking-atlas/trekking-atlas3.jpg',
    },
    {
        id: '29',
        slug: 'gorgas-todra',
        title_es: 'Excursión a las Gargantas del Todra',
        title_en: 'Todra Gorges Excursion',
        category: 'montana',
        destination: 'Ouarzazate',
        difficulty: 'moderado',
        duration_days: 1,
        price_from_usd: 95,
        rating: 4.6,
        reviews_count: 67,
        image: '/images/trekking-atlas/trekking-atlas3.jpg',
    },
    {
        id: '30',
        slug: 'escalada-todra',
        title_es: 'Escalada en las Gargantas del Todra',
        title_en: 'Climbing in Todra Gorges',
        category: 'montana',
        destination: 'Ouarzazate',
        difficulty: 'dificil',
        duration_days: 2,
        price_from_usd: 180,
        rating: 4.8,
        reviews_count: 23,
        image: '/images/trekking-atlas/trekking-atlas3.jpg',
    },
    {
        id: '31',
        slug: 'marrakech-toubkal-invierno',
        title_es: 'Toubkal en Invierno con Piolet',
        title_en: 'Winter Toubkal with Ice Axe',
        category: 'montana',
        destination: 'Marrakech',
        difficulty: 'extremo',
        duration_days: 3,
        price_from_usd: 380,
        rating: 4.9,
        reviews_count: 15,
        image: '/images/trekking-atlas/trekking-atlas5.jpg',
    },
    {
        id: '32',
        slug: 'rifugio-toubkal',
        title_es: 'Trekking al Refugio de Toubkal',
        title_en: 'Trekking to Toubkal Refuge',
        category: 'montana',
        destination: 'Marrakech',
        difficulty: 'moderado',
        duration_days: 2,
        price_from_usd: 175,
        rating: 4.8,
        reviews_count: 45,
        image: '/images/trekking-atlas/trekking-atlas5.jpg',
    },

    // LOCALES (6)
    {
        id: '11',
        slug: 'cocina-marroqui',
        title_es: 'Clase de Cocina Marroquí',
        title_en: 'Moroccan Cooking Class',
        category: 'locales',
        destination: 'Marrakech',
        difficulty: 'facil',
        duration_days: 1,
        price_from_usd: 55,
        rating: 4.9,
        reviews_count: 112,
        image: '/images/marrakech/marrakech2.jpg',
    },
    {
        id: '33',
        slug: 'cena-familia',
        title_es: 'Cena con Familia Local',
        title_en: 'Dinner with Local Family',
        category: 'locales',
        destination: 'Marrakech',
        difficulty: 'facil',
        duration_days: 1,
        price_from_usd: 40,
        rating: 4.8,
        reviews_count: 89,
        image: '/images/marrakech/marrakech2.jpg',
    },
    {
        id: '34',
        slug: 'hammam',
        title_es: 'Experiencia de Hammam Tradicional',
        title_en: 'Traditional Hammam Experience',
        category: 'locales',
        destination: 'Marrakech',
        difficulty: 'facil',
        duration_days: 1,
        price_from_usd: 35,
        rating: 4.7,
        reviews_count: 145,
        image: '/images/marrakech/marrakech2.jpg',
    },
    {
        id: '35',
        slug: 'taller-zellige',
        title_es: 'Taller de Azulejos Zellige',
        title_en: 'Zellige Tiles Workshop',
        category: 'locales',
        destination: 'Fez',
        difficulty: 'facil',
        duration_days: 1,
        price_from_usd: 65,
        rating: 4.9,
        reviews_count: 56,
        image: '/images/marrakech/marrakech2.jpg',
    },
    {
        id: '36',
        slug: 'noche-berber',
        title_es: 'Noche Tradicional Bereber',
        title_en: 'Traditional Berber Night',
        category: 'locales',
        destination: 'Merzouga',
        difficulty: 'facil',
        duration_days: 1,
        price_from_usd: 75,
        rating: 4.8,
        reviews_count: 92,
        image: '/images/marrakech/marrakech2.jpg',
    },
    {
        id: '37',
        slug: 'visita-berber',
        title_es: 'Visita a Aldea Bereber y Té de Menta',
        title_en: 'Berber Village Visit and Mint Tea',
        category: 'locales',
        destination: 'Marrakech',
        difficulty: 'facil',
        duration_days: 1,
        price_from_usd: 45,
        rating: 4.7,
        reviews_count: 134,
        image: '/images/marrakech/marrakech2.jpg',
    },
];
